<?php

return [


    'task_title' => 'Task Title',
    'task_description' => 'Task Description',
    'task_status' => 'Task Status',
    'task_priority' => 'Task Priority',
    'task_date' => 'Task Date',
    'task_actions' => 'Task Actions',
    'create_task' => 'Create Task',
    'update_task' => 'Update Task',
    'task_list' => 'Task List',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'archive' => 'Archive',
    'select_priority' => 'Select priority',
    'select_status' => 'Select status',
    'reminder' => 'Remind users at',

    'low' => 'Low',
    'high' => 'High',
    'medium' => 'Medium',
    'to-do' => 'To Do',
    'yes_done' => 'Yes it is done',
    'task_user' => 'Select user for task',
    'in-progress' => 'In Progress',
    'done' => 'Done',
    'time_line' => 'Time Line',
    'status'=>'Status',
    'task_cancelled'=>'Task is cancelled',
    'priority'=>'Priority',
    'date'=>'Date',
    'task_updated'=>'Task Updated',
    'task_created'=>'Task Created',
    'task_deleted'=>'Task Deleted',
    'created_by'=>'Created By :name',
    'this_task_done'=>'Task will be marked as Done',
    'task_done'=>'Task is marked as DONE',
    'are_you_sure'=>"Are you sure?",
    'this_task_will_be_deleted'=>"This task will be deleted",
    'enter_pw'=>"Please enter your password for authentication",
    'this_task_will_be_cancelled'=>"This task will be cancelled",
    'yes_cancel_task'=>"Yes cancel task",
    'no'=>"No",
    'enter_reason'=>"Enter Reason",
    'cancel_reason'=>"Cancel Reason",
    'tasks'=>"Tasks for :name",
    'this_task_cancelled'=>"This task is cancelled",
    'actions'=>"Actions",
    'start_at'=>"Starts At",
    'end_at'=>"Ends At",
    'send_all_client'=>'Send All Clients',
    'send_all_driver'=>'Send All Drivers',
    'send_all_driver_company'=>'Send All Driver Companies',
    'sent_to'=>'Sent to',
    'send_all_manager'=>'Send All Managers',
    'yes'=>'Yes',
    'inform_with_email'=>'Inform with email',
    'additional_email'=>'Additional Emails',
    'email_subject'=>'Email Subject',
    'task_assigned_to'=>'Assigned To',
    'user_status'=>'User Status',
    'assigned_user'=>'Assigned User',
    'assigned_users'=>'Assigned Users',
    'update_date'=>'Last Updated',
    'sent_to_users'=>'Sent to :number users',
    'sent_all'=>'all :value',
    'task_info'=>'Task Info',
    'all_tasks' => 'All Tasks',
    'none' => 'None',
    'okay' => 'Okay',
    'task_is_updated' => 'Task is updated',
    'view_task' => 'View Task',
    'create_update_task' => 'Create/Update Task',

////notification//////////////////////
    'task_created_notification'=>':title titled task created by :name',
    'task_update_notification'=>':title titled task updated by :name',
    'new_tasks'=>'New Tasks',
    'open_tasks'=>'Open Tasks',
    'completed_tasks'=>'Completed Tasks',
    'tasks_in_progress'=>'Tasks in progress',
    'to_do_tasks'=>'To-do Tasks',
    'cancelled_tasks'=>'Cancelled Tasks',
    'date_range'=>'Date Range',
    'created_by_user'=>'Task created by :name',
    'today'=>'Today',
    'yesterday'=>'Yesterday',
    'last_7_days'=>'Last 7 Days',
    'last_30_days'=>'Last 30 Days',
    'this_month'=>'This Month',
    'last_month'=>'Last Month',
////notification//////////////////////


];
